name: study_planner
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider_android:
  http:
  firebase_core:
  cloud_firestore:
  firebase_auth:
  flutter_local_notifications:
  shared_preferences:
  google_fonts:
  fl_chart:
  gemini:
  google_generative_ai:
  intl:
  cupertino_icons: ^1.0.8
  file_picker: ^9.0.1  # ✅ Keep only one instance
  syncfusion_flutter_pdf: ^24.1.47  # ✅ Add Syncfusion PDF package

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/start.png
